---
- hosts: localhost
  become: true
  become_method: sudo 
  tasks:
  - name: Install python
    apt: 
      name: {{ item }} 
      state: latest
    with_items:
     - python
    when: ansible_distribution == 'Ubuntu' 